apiVersion: v1
kind: ConfigMap
metadata:
  name: common-config
data:
  SPRING_PROFILES_ACTIVE: dev
  EUREKA_URL: http://service-discovery:8761/eureka/
  CONFIG_SERVER_URL: http://cloud-config:9296
  ZIPKIN_URL: http://zipkin:9411
